### ISSUE TITLE
what is the meaning of chord class "X"?

### ISSUE THREAD

**Issue by kylemcdonald** [bmcfee/crema#29]
From the mir_eval documentation I figured out that `N` is "no chord", but I can't figure out `X` 🤔

My best guess right now is something like "there's a chord, but not sure which one"?

I have a dataset of cover songs where `X` makes up around 10% of all the output. Any hints would be very much appreciated 🙏

**Comment by bmcfee** [comment]
X is used for out-of-gamut chords. Usually that's power chords, but in general it could be anything that doesn't map onto Harte's (extended) grammar.
