### ISSUE TITLE
Installing crema from pypi results in a wrong dependency

### ISSUE THREAD

**Issue by miqwit** [bmcfee/crema#31]
It is indeed installing librosa 0.5.0 whereas, as described in this project's setup, at least 0.6 must be installed.
By default, when doing `pip install crema` it's not useable. First error poping in is that `times_like` is missing.

**Comment by ctralie** [comment]
Not sure if this helps you, but I was able to get it to work on my machine by installing a conda environment with Python 3.6, then installing crema from this respository, then installing libroa 0.6.1

**Comment by miqwit** [comment]
Yep! it's what I did. It's just that the way the library is packaged is referencing a wrong version. I wanted to alert the developer about that.

**Comment by bmcfee** [comment]
Thanks for catching this, and sorry for the severe lag in updates here.  This is resolved now on main, and should work out of the box in the next release.
